name: Setup

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'

    - name: Setup PNPM
      uses: pnpm/setup@v2
      with:
        version: 12

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
