name: Build library package
run-name: ${{ github.actor }} is building library package
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/setup.yml

      - name: Build
        run: pnpm build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/setup.yml

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
